version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - wallet-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: wallet-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - wallet-network

  db:
    image: mysql:8.0
    container_name: wallet-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: digital_wallet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: wallet
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - wallet-network

  redis:
    image: redis:alpine
    container_name: wallet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
